/*
 * Stoatworks Labs - About window data for gaffer.
 *
 * Normally GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json, which is the one place these facts are written down.
 * This copy is hand-written in the generated shape because there is no website
 * entry yet; the next sync should overwrite it once there is.
 *
 * `guide` and `page` are empty strings ON PURPOSE. The About block leaves a
 * missing link out rather than drawing a button that opens a 404.
 *
 * `version` here is a fallback read from this repo's own manifest at sync time.
 * Anything with a build step injects the real one at build time and overrides
 * this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "gaffer";
    inline constexpr auto slug = "gaffer";
    inline constexpr auto hook = "Audio-reactive lens: bass rattle and rack focus, on depth";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/gaffer";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
